// Rae's vocabulary-specific ASR alternatives. These are intentionally kept out
// of the generic matcher so another activity can choose its own vocabulary.
export const RAE_ALIASES = {
  a: ['ay', 'eh', 'hey'],
  b: ['bee', 'be', 'bea', 'bees'],
  c: ['sea', 'see', 'si', 'seed'],
  o: ['oh', 'owe', 'zero'],
  s: ['es', 'ass', 'yes'],
  m: ['em', 'am', 'mm'],
  one: ['won', 'wan', '1'],
  two: ['to', 'too', 'tu', '2'],
  three: ['tree', 'free', 'threes', '3'],
  four: ['for', 'fore', 'foor', '4'],
  five: ['hive', 'fife', '5'],
  cat: ['cats', 'kat', 'kitty'],
  dog: ['dogs', 'doggy', 'dock'],
  bus: ['buzz', 'boss', 'busses'],
  ball: ['bore', 'bao', 'balls'],
  fish: ['fishy', 'fis', 'fishes'],
  bird: ['birds', 'bird bird', 'burt'],
  cake: ['cakes', 'cake cake', 'kek'],
  star: ['stars', 'staa', 'sta'],
  duck: ['ducks', 'duck duck', 'dark'],
  egg: ['eggs', 'egg egg', 'x'],
  stop: ['stopp', 'stob', 'star p'],
  go: ['goh', 'gogo', 'go go'],
  wheee: ['we', 'wee', 'whee', 'weee', 'yay', 'wow', 'woah'],
  moon: ['moo', 'moons'],
  sun: ['son', 'sunny'],
  tree2: ['tree'],
  boat: ['boats', 'bot', 'both'],
  crab: ['crabs', 'grab'],
  shell: ['shells', 'shall'],
  kite: ['kites', 'kai', 'kind'],
  car: ['cars', 'kar'],
  bell: ['bells', 'bail', 'bao'],
  'ring ring': ['ring', 'ring ring ring', 'ling ling'],
  // These trigger always-on desktop commands, so narration words stay out.
  left: ['lef', 'lift', 'laft', 'left left', 'lept'],
  right: ['rite', 'write', 'right right', 'wight'],
  faster: ['fast', 'faster faster', 'fasta', 'vaster', 'fassa'],
  slower: ['slow', 'slower slower', 'sloa', 'slowa', 'lower'],
  apple: ['appo', 'appu', 'abble', 'apo'],
  banana: ['nana', 'nanana', 'banan', 'panana'],
  rabbit: ['wabbit', 'wabbi', 'rabbi'],
  frog: ['fog', 'fwog', 'frag'],
  elephant: ['ephant', 'elphant', 'ellie', 'efelant'],
  butterfly: ['butfly', 'buttfly', 'flutterby', 'butterfy'],
  strawberry: ['strawbee', 'strabby', 'sawberry'],
  pineapple: ['pineappo', 'pine', 'appo'],
  watermelon: ['watamelon', 'melon', 'wawa'],
  triangle: ['trangle', 'tri', 'triangoo'],
  circle: ['circoo', 'sircle', 'circ'],
  square: ['squares', 'sqway', 'skware'],
  // This is the effective duplicate-object-key value from the old matcher.
  flower: ['flowa', 'fowa', 'flowers'],
  yellow: ['yellow yellow', 'lello', 'yeyo'],
  monkey: ['monkeys', 'munky', 'monki'],
  snail: ['snails', 'nail', 'snai'],
  turtle: ['tuttle', 'tuɾtle', 'turto'],
  penguin: ['pengin', 'pengu', 'pingu'],
  umbrella: ['brella', 'umbella', 'umbwella'],
  pumpkin: ['punkin', 'pumkin', 'pumpki'],
  mushroom: ['mushoom', 'moom', 'mushy'],
  carrot: ['cawwot', 'carot', 'cawot'],
  balloon: ['baloon', ' balloo', 'bayoon'],
  train: ['choo choo', 'chtrain', 'twain'],
  plane: ['aeroplane', 'airplane', 'pane', 'pwane'],
};
